#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

/usr/sbin/groupadd -g 5092 dsapid
/usr/sbin/useradd -u 5092 -g dsapid -d /opt/dsapid -s /usr/bin/bash dsapid

if ! projects -l dsapid >/dev/null 2>&1; then
  LANG=C projadd -U dsapid -G dsapid \
    -K "process.max-file-descriptor=(basic,16384,deny)" \
    -c "Dataset Image Server" dsapid
fi

svccfg import /root/dsapid.xml

# Clean up
echo "* Cleaning up."
pkgin clean
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
